all:
  children:
    threlium_hosts:
      hosts:
        sut:
          ansible_connection: docker
          ansible_host: "{{ e2e_sut_container_id }}"
          ansible_python_interpreter: /usr/bin/python3
